import = [
  "~/.config/alacritty/themes/themes/challenger_deep.toml"
]
# TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.3
blur = true

[font]
normal.family = "MesloLGS NF"

size = 18
